---
name: URI-geo
version: 0.02
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: The geo URI scheme.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Test::More: 0
  URI: 0
provides:
  URI::geo:
    file: lib/URI/geo.pm
    version: 0.02
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
