---
name: URI-geo
version: 0.04
author:
  - 'Andy Armstrong <andy@hexten.net>'
abstract: The geo URI scheme.
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=URI-geo
  license: ~
  repository: https://svn.hexten.net/andy/Perl/URI/URI-geo/trunk
requires:
  Test::More: 0
  URI: 0
provides:
  URI::geo:
    file: lib/URI/geo.pm
    version: 0.04
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
